### ISSUE TITLE
User can add plans to their itinerary

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a plan and add activities to their plans.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user fills out a form that contains information on 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-07 at 10 10 12 AM](https://user-images.githubusercontent.com/82190583/132384382-7a75fd21-b111-4552-89cf-cba0cafc08fc.png)
![Screen Shot 2021-09-07 at 10 11 57 AM](https://user-images.githubusercontent.com/82190583/132384662-86488c5d-d091-45f9-947b-a2e9eb1f4fc6.png)
![Screen Shot 2021-09-07 at 10 12 06 AM](https://user-images.githubusercontent.com/82190583/132384665-55748b36-38bd-4c64-92b6-5f659aa90c56.png)
![Screen Shot 2021-09-07 at 10 12 17 AM](https://user-images.githubusercontent.com/82190583/132384666-1a52bc0a-1369-41a8-b2be-52ac8abaf37f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have 3 tables. 
- [x] There will be a plans , users, and activities table. 
- [x] The plans table will have a serial type planId that is a foreign key with the planId in the activities table, an integer type userId and a text type date field. 
- [x] The activities table will have a serial activityId, an integer planId which is a foreign key with the planId in the plans table. There is a text type details field, a text type location, an integer type pictureUrl, and an integer type amount field. 
- [x] In the users table There is a serial type userId that is a foreign key with the userId in the plans table, a text type username, and a text type hashedPassword field. 

### ☁️ Server

- [x] Update `server/index.js` to ... send post requests to the plans route
- [x] test with HTTPie
- [x] create an sql variable  named insertPlan with a template literal that inserts the plan name, planId and the date into the plans table. 
- [x] create another sql variable named insertActivity with a template literal that inserts the activityName, details, activityId, pictureUrl into the table. 
- [x]  query the database with the params for plan name planId and date. 
- [x] query the database with the params for details and activityName
- [x] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...  hold the plans in an accordion with the activity name in the header and the details in the body of the accordion.
- [ ] Update component to ... include each activity for the plan.
- [x] create a form component 
- [x] import the image
- [x] create the hamburger icon in the top left corner.
- [x] add the image for traveldex 
- [ ] render the title and date on the plan page along with the accordion. 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
