### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/final-project#14]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Remove all uncecessary files and directories
- [x] use lower-kebab-case for all file and directory names
- [x] uninstall dependencies that were added but never actually used
- [x] clean up all HTML files according to the guide
- [x] clean up all CSS files according to the guide
- [x] clean up all javascript/jsx files according to the guide
