### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/final-project#16]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [ ] update repository name on github
- [ ] update links in resume, linkedIn profile
- [ ] profile readme
- [ ] project readme 
- [ ] update <title></title>
- [ ] add a one word sentence for ____ who want to _____.
- [ ] put a link in to your live deployment in the website field.
- [ ] leave Topics empty
- [ ] update favicon
- [ ] remove unprofessional content
- [ ] make your project sharable
