### ISSUE TITLE
User can read their plans from the itinerary

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can see their plans and the activities they made.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the menu bar a modal pops out and sees their plans. they can click into the plans and see their plan they've made. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="170" alt="Screen Shot 2021-09-11 at 11 05 48 AM" src="https://user-images.githubusercontent.com/82190583/132957185-b51be64b-6d67-4d81-8b6e-0c900a99118a.png">
<img width="167" alt="Screen Shot 2021-09-11 at 11 05 55 AM" src="https://user-images.githubusercontent.com/82190583/132957186-b73c8bf2-4bff-49df-a166-558cb155f0ea.png">
<img width="161" alt="Screen Shot 2021-09-11 at 11 06 05 AM" src="https://user-images.githubusercontent.com/82190583/132957188-14baafd6-3166-48af-924f-2a7a9ac5df97.png">
<img width="281" alt="Screen Shot 2021-09-11 at 11 06 40 AM" src="https://user-images.githubusercontent.com/82190583/132957190-e4c035fb-27b0-4a28-867f-a407f81823d1.png">
<img width="286" alt="Screen Shot 2021-09-11 at 11 06 49 AM" src="https://user-images.githubusercontent.com/82190583/132957191-ee6ca0df-6dc4-4c0e-9155-76a952bcef9c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...  receive get requests from the client, query the db for the request. Get the response from the database and send a request back to the client with either a 201 or 400 response code. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...hold all the activities inside an accordion. 
- [x] Update component to ... have activities on the correct plan. 
- [x] create an app drawer that slides out when the menu button is clicked. 
- [x] attach an unordered list of plans on the modal.
- [x] create the "plans" page and link it with hash routing.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
