### ISSUE TITLE
User can delete plans from the itinerary

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete plans from their. itinerary

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user wants to delete a plan they can click an icon next to the plan name and delete the plan, and if they want to delete an activity they can click into an activity and click the delete button inside the activity form. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="193" alt="Screen Shot 2021-09-16 at 3 05 54 PM" src="https://user-images.githubusercontent.com/82190583/133692342-446f2276-ab63-4317-aab9-3151e2408230.png">
<img width="187" alt="Screen Shot 2021-09-16 at 3 06 07 PM" src="https://user-images.githubusercontent.com/82190583/133692365-c0fff730-200b-4436-9cde-28be4b8701d3.png">
<img width="184" alt="Screen Shot 2021-09-16 at 3 06 13 PM" src="https://user-images.githubusercontent.com/82190583/133692379-ab167323-52af-4db9-856f-4b97a0154ba8.png">
<img width="186" alt="Screen Shot 2021-09-16 at 4 32 54 PM" src="https://user-images.githubusercontent.com/82190583/133701614-aca017c9-e599-42a1-9972-1319e3b2a44a.png">
<img width="559" alt="Screen Shot 2021-09-16 at 3 08 07 PM" src="https://user-images.githubusercontent.com/82190583/133692489-ac39a27a-6ce7-44d6-80c7-e54766fe210f.png">
<img width="560" alt="Screen Shot 2021-09-16 at 3 08 17 PM" src="https://user-images.githubusercontent.com/82190583/133692497-9c8dfe7f-460b-4dc1-9045-3cafeeb5131c.png">
<img width="562" alt="Screen Shot 2021-09-16 at 3 10 21 PM" src="https://user-images.githubusercontent.com/82190583/133692509-7ff7b08e-48a0-48ed-8596-c652e8623dea.png">
<img width="560" alt="Screen Shot 2021-09-16 at 3 08 53 PM" src="https://user-images.githubusercontent.com/82190583/133692519-3ee9e5d8-8e4f-48f5-8d86-b54fafa19dab.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ... handle delete requests for plans
- [x] the url path will take /api/plans/:planId
- [x] get the req.params and assign it to a variable
- [x] create a sql variable where we delete from the "plans" table 
- [x] in the where clause use "planId" and set it equal to a parameterized query. 
- [x] query the database
- [x] then 😉  set a variable to the result.rows[0] and send a response to the client. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update result page component to ... have a trash can icon on my results page. 
- [x] create a modal with yes and no buttons. 
- [x] add a isOpen state and create a method that checks to see if the state is true or false. 
- [x] bind the method to this
- [x] attach the method to the trash can icon onClick.
- [x] create another method to handle deleting the request. 
- [x] Inside the method send a fetch request with method "DELETE" 
### 🧑‍⚕️ Clean Up

- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
