### ISSUE TITLE
User can add amount if activities cost money

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an amount if activities cost money. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can add a set amount of money to their activities that will show up on the result page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what t
![Screen Shot 2021-09-17 at 5 06 14 PM](https://user-images.githubusercontent.com/82190583/133864968-67a6e0aa-38b6-470a-b50b-618654c75be2.png)
![Screen Shot 2021-09-17 at 5 06 20 PM](https://user-images.githubusercontent.com/82190583/133864969-50fef602-17ac-41fd-ada0-59e99dafc412.png)
![Screen Shot 2021-09-17 at 5 06 41 PM](https://user-images.githubusercontent.com/82190583/133864971-a82e0c6e-c953-47e8-b678-eb0a87d3ec03.png)
![Screen Shot 2021-09-17 at 5 06 49 PM](https://user-images.githubusercontent.com/82190583/133864972-1d2674ec-7fc8-43fc-af33-c042088ace66.png)
he app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ... include an "amount" in the activities table. 
- [x] in the terminal run npm run db:import to import the new database.
### ☁️ Server

- [x] Update `server/index.js` to ... include "amount" in the sql variables of the get requests using :planId and :activityId
- [x] test with HTTPie
- [x] include"amount"  inside the post and patch method for activities and activityId.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] add a property in the state for amount
- [x] update componentDidMount method to include the amount inside the setState method. 
 - [x] update the patch and post requests inside the handleSubmit method on the activityForm to include the amount. 
- [x] include the amount inside both destructured objects.
- [x] Update activityForm component to ... include amount input inside the render method.
- [x] create a method that sets the state of the amount to whatever is input in the form. 
- [x] add an h3 element to the result page and pass the amount as a prop

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
